package com.teamodoro.ui.theme

import androidx.compose.ui.graphics.Color

// Work / Focus phase — Red palette
val WorkPrimary = Color(0xFFB71C1C)
val WorkOnPrimary = Color(0xFFFFFFFF)
val WorkPrimaryContainer = Color(0xFFFFCDD2)
val WorkOnPrimaryContainer = Color(0xFF7F0000)
val WorkSecondary = Color(0xFFE53935)
val WorkBackground = Color(0xFFFFF8F8)
val WorkSurface = Color(0xFFFFF8F8)
val WorkOnBackground = Color(0xFF1C0000)
val WorkOnSurface = Color(0xFF1C0000)
val WorkDarkPrimary = Color(0xFFFFB4AB)
val WorkDarkOnPrimary = Color(0xFF690005)
val WorkDarkPrimaryContainer = Color(0xFF93000A)
val WorkDarkOnPrimaryContainer = Color(0xFFFFDAD6)
val WorkDarkSecondary = Color(0xFFFFB4AB)
val WorkDarkBackground = Color(0xFF201A1A)
val WorkDarkSurface = Color(0xFF201A1A)
val WorkDarkOnBackground = Color(0xFFEDE0DF)
val WorkDarkOnSurface = Color(0xFFEDE0DF)

// Break phase — Blue palette
val BreakPrimary = Color(0xFF0D47A1)
val BreakOnPrimary = Color(0xFFFFFFFF)
val BreakPrimaryContainer = Color(0xFFBBDEFB)
val BreakOnPrimaryContainer = Color(0xFF002171)
val BreakSecondary = Color(0xFF1E88E5)
val BreakBackground = Color(0xFFF8FBFF)
val BreakSurface = Color(0xFFF8FBFF)
val BreakOnBackground = Color(0xFF00101C)
val BreakOnSurface = Color(0xFF00101C)
val BreakDarkPrimary = Color(0xFFA6C8FF)
val BreakDarkOnPrimary = Color(0xFF003062)
val BreakDarkPrimaryContainer = Color(0xFF004787)
val BreakDarkOnPrimaryContainer = Color(0xFFD5E3FF)
val BreakDarkSecondary = Color(0xFFA6C8FF)
val BreakDarkBackground = Color(0xFF191C20)
val BreakDarkSurface = Color(0xFF191C20)
val BreakDarkOnBackground = Color(0xFFE1E2E8)
val BreakDarkOnSurface = Color(0xFFE1E2E8)
